name: Sync Intervals Data

on:
  schedule:
    - cron: "0 5 * * *"

  workflow_dispatch:

  permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:

      - name: Download repository
        uses: actions/checkout@v4

      - name: Haal activiteiten op
        env:
          API_KEY: ${{ secrets.INTERVALS_API_KEY }}
        run: |
          curl \
          -u ":$API_KEY" \
          "https://intervals.icu/api/v1/athlete/i174459/activities?oldest=2025-01-01" \
          -o data/activities.json

      - name: Bewaar nieuwe data
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add data/activities.json
          git commit -m "Update Intervals data" || exit 0
          git push
